"""Character datasets for each language writing system."""
from __future__ import annotations

HIRAGANA: list[dict] = [
    {"glyph": "あ", "romanization": "a", "pronunciation": "ah", "example_glyph": "あさ", "example_meaning": "Morning", "image": "🌅"},
    {"glyph": "い", "romanization": "i", "pronunciation": "ee", "example_glyph": "いぬ", "example_meaning": "Dog", "image": "🐶"},
    {"glyph": "う", "romanization": "u", "pronunciation": "oo", "example_glyph": "うみ", "example_meaning": "Sea", "image": "🌊"},
    {"glyph": "え", "romanization": "e", "pronunciation": "eh", "example_glyph": "えき", "example_meaning": "Station", "image": "🚉"},
    {"glyph": "お", "romanization": "o", "pronunciation": "oh", "example_glyph": "おちゃ", "example_meaning": "Tea", "image": "🍵"},
    {"glyph": "か", "romanization": "ka", "pronunciation": "kah", "example_glyph": "かさ", "example_meaning": "Umbrella", "image": "☂️"},
    {"glyph": "き", "romanization": "ki", "pronunciation": "kee", "example_glyph": "き", "example_meaning": "Tree", "image": "🌳"},
    {"glyph": "く", "romanization": "ku", "pronunciation": "koo", "example_glyph": "くも", "example_meaning": "Cloud", "image": "☁️"},
    {"glyph": "け", "romanization": "ke", "pronunciation": "keh", "example_glyph": "けさ", "example_meaning": "This morning", "image": "🌄"},
    {"glyph": "こ", "romanization": "ko", "pronunciation": "koh", "example_glyph": "ここ", "example_meaning": "Here", "image": "📍"},
    {"glyph": "さ", "romanization": "sa", "pronunciation": "sah", "example_glyph": "さかな", "example_meaning": "Fish", "image": "🐟"},
    {"glyph": "し", "romanization": "shi", "pronunciation": "shee", "example_glyph": "しろ", "example_meaning": "White", "image": "⚪"},
    {"glyph": "す", "romanization": "su", "pronunciation": "soo", "example_glyph": "すし", "example_meaning": "Sushi", "image": "🍣"},
    {"glyph": "せ", "romanization": "se", "pronunciation": "seh", "example_glyph": "せんせい", "example_meaning": "Teacher", "image": "👩‍🏫"},
    {"glyph": "そ", "romanization": "so", "pronunciation": "soh", "example_glyph": "そら", "example_meaning": "Sky", "image": "🌤️"},
    {"glyph": "た", "romanization": "ta", "pronunciation": "tah", "example_glyph": "たこ", "example_meaning": "Octopus", "image": "🐙"},
    {"glyph": "ち", "romanization": "chi", "pronunciation": "chee", "example_glyph": "ちず", "example_meaning": "Map", "image": "🗺️"},
    {"glyph": "つ", "romanization": "tsu", "pronunciation": "tsoo", "example_glyph": "つき", "example_meaning": "Moon", "image": "🌙"},
    {"glyph": "て", "romanization": "te", "pronunciation": "teh", "example_glyph": "て", "example_meaning": "Hand", "image": "✋"},
    {"glyph": "と", "romanization": "to", "pronunciation": "toh", "example_glyph": "ともだち", "example_meaning": "Friend", "image": "👫"},
    {"glyph": "な", "romanization": "na", "pronunciation": "nah", "example_glyph": "なつ", "example_meaning": "Summer", "image": "☀️"},
    {"glyph": "に", "romanization": "ni", "pronunciation": "nee", "example_glyph": "にく", "example_meaning": "Meat", "image": "🥩"},
    {"glyph": "ぬ", "romanization": "nu", "pronunciation": "noo", "example_glyph": "ぬの", "example_meaning": "Cloth", "image": "🧵"},
    {"glyph": "ね", "romanization": "ne", "pronunciation": "neh", "example_glyph": "ねこ", "example_meaning": "Cat", "image": "🐱"},
    {"glyph": "の", "romanization": "no", "pronunciation": "noh", "example_glyph": "のむ", "example_meaning": "To drink", "image": "🥤"},
    {"glyph": "は", "romanization": "ha", "pronunciation": "hah", "example_glyph": "はな", "example_meaning": "Flower", "image": "🌸"},
    {"glyph": "ひ", "romanization": "hi", "pronunciation": "hee", "example_glyph": "ひ", "example_meaning": "Fire", "image": "🔥"},
    {"glyph": "ふ", "romanization": "fu", "pronunciation": "foo", "example_glyph": "ふね", "example_meaning": "Ship", "image": "🚢"},
    {"glyph": "へ", "romanization": "he", "pronunciation": "heh", "example_glyph": "へや", "example_meaning": "Room", "image": "🏠"},
    {"glyph": "ほ", "romanization": "ho", "pronunciation": "hoh", "example_glyph": "ほん", "example_meaning": "Book", "image": "📚"},
    {"glyph": "ま", "romanization": "ma", "pronunciation": "mah", "example_glyph": "まど", "example_meaning": "Window", "image": "🪟"},
    {"glyph": "み", "romanization": "mi", "pronunciation": "mee", "example_glyph": "みず", "example_meaning": "Water", "image": "💧"},
    {"glyph": "む", "romanization": "mu", "pronunciation": "moo", "example_glyph": "むし", "example_meaning": "Insect", "image": "🐛"},
    {"glyph": "め", "romanization": "me", "pronunciation": "meh", "example_glyph": "め", "example_meaning": "Eye", "image": "👁️"},
    {"glyph": "も", "romanization": "mo", "pronunciation": "moh", "example_glyph": "もも", "example_meaning": "Peach", "image": "🍑"},
    {"glyph": "や", "romanization": "ya", "pronunciation": "yah", "example_glyph": "やま", "example_meaning": "Mountain", "image": "⛰️"},
    {"glyph": "ゆ", "romanization": "yu", "pronunciation": "yoo", "example_glyph": "ゆき", "example_meaning": "Snow", "image": "❄️"},
    {"glyph": "よ", "romanization": "yo", "pronunciation": "yoh", "example_glyph": "よる", "example_meaning": "Night", "image": "🌃"},
    {"glyph": "ら", "romanization": "ra", "pronunciation": "rah", "example_glyph": "らくだ", "example_meaning": "Camel", "image": "🐪"},
    {"glyph": "り", "romanization": "ri", "pronunciation": "ree", "example_glyph": "りんご", "example_meaning": "Apple", "image": "🍎"},
    {"glyph": "る", "romanization": "ru", "pronunciation": "roo", "example_glyph": "るす", "example_meaning": "Absence", "image": "🚪"},
    {"glyph": "れ", "romanization": "re", "pronunciation": "reh", "example_glyph": "れきし", "example_meaning": "History", "image": "📜"},
    {"glyph": "ろ", "romanization": "ro", "pronunciation": "roh", "example_glyph": "ろく", "example_meaning": "Six", "image": "6️⃣"},
    {"glyph": "わ", "romanization": "wa", "pronunciation": "wah", "example_glyph": "わたし", "example_meaning": "I / me", "image": "🙋"},
    {"glyph": "を", "romanization": "wo", "pronunciation": "oh", "example_glyph": "ほんを", "example_meaning": "Book (object)", "image": "📖"},
    {"glyph": "ん", "romanization": "n", "pronunciation": "n", "example_glyph": "ほん", "example_meaning": "Book", "image": "📕"},
]

SPANISH_ALPHABET: list[dict] = [
    {"glyph": "A", "romanization": "a", "pronunciation": "ah", "example_glyph": "Avión", "example_meaning": "Airplane", "image": "✈️"},
    {"glyph": "B", "romanization": "be", "pronunciation": "bay", "example_glyph": "Buenos días", "example_meaning": "Good morning", "image": "☀️"},
    {"glyph": "C", "romanization": "ce", "pronunciation": "say", "example_glyph": "Casa", "example_meaning": "House", "image": "🏠"},
    {"glyph": "D", "romanization": "de", "pronunciation": "day", "example_glyph": "Día", "example_meaning": "Day", "image": "📅"},
    {"glyph": "E", "romanization": "e", "pronunciation": "eh", "example_glyph": "Escuela", "example_meaning": "School", "image": "🏫"},
    {"glyph": "F", "romanization": "efe", "pronunciation": "eh-fay", "example_glyph": "Familia", "example_meaning": "Family", "image": "👨‍👩‍👧"},
    {"glyph": "G", "romanization": "ge", "pronunciation": "hay", "example_glyph": "Gato", "example_meaning": "Cat", "image": "🐱"},
    {"glyph": "H", "romanization": "hache", "pronunciation": "ah-chay", "example_glyph": "Hola", "example_meaning": "Hello", "image": "👋"},
    {"glyph": "I", "romanization": "i", "pronunciation": "ee", "example_glyph": "Iglesia", "example_meaning": "Church", "image": "⛪"},
    {"glyph": "J", "romanization": "jota", "pronunciation": "ho-tah", "example_glyph": "Jardín", "example_meaning": "Garden", "image": "🌻"},
    {"glyph": "K", "romanization": "ka", "pronunciation": "kah", "example_glyph": "Kilo", "example_meaning": "Kilogram", "image": "⚖️"},
    {"glyph": "L", "romanization": "ele", "pronunciation": "eh-lay", "example_glyph": "Libro", "example_meaning": "Book", "image": "📚"},
    {"glyph": "M", "romanization": "eme", "pronunciation": "eh-may", "example_glyph": "Mesa", "example_meaning": "Table", "image": "🪑"},
    {"glyph": "N", "romanization": "ene", "pronunciation": "eh-nay", "example_glyph": "Noche", "example_meaning": "Night", "image": "🌙"},
    {"glyph": "Ñ", "romanization": "eñe", "pronunciation": "eh-nyeh", "example_glyph": "Niño", "example_meaning": "Boy", "image": "👦"},
    {"glyph": "O", "romanization": "o", "pronunciation": "oh", "example_glyph": "Ojo", "example_meaning": "Eye", "image": "👁️"},
    {"glyph": "P", "romanization": "pe", "pronunciation": "pay", "example_glyph": "Pan", "example_meaning": "Bread", "image": "🍞"},
    {"glyph": "Q", "romanization": "cu", "pronunciation": "coo", "example_glyph": "Queso", "example_meaning": "Cheese", "image": "🧀"},
    {"glyph": "R", "romanization": "erre", "pronunciation": "eh-rreh", "example_glyph": "Rojo", "example_meaning": "Red", "image": "🔴"},
    {"glyph": "S", "romanization": "ese", "pronunciation": "eh-say", "example_glyph": "Sol", "example_meaning": "Sun", "image": "☀️"},
    {"glyph": "T", "romanization": "te", "pronunciation": "tay", "example_glyph": "Té", "example_meaning": "Tea", "image": "🍵"},
    {"glyph": "U", "romanization": "u", "pronunciation": "oo", "example_glyph": "Uno", "example_meaning": "One", "image": "1️⃣"},
    {"glyph": "V", "romanization": "ve", "pronunciation": "vay", "example_glyph": "Vaca", "example_meaning": "Cow", "image": "🐄"},
    {"glyph": "W", "romanization": "doble ve", "pronunciation": "doh-blah vay", "example_glyph": "Web", "example_meaning": "Web", "image": "🌐"},
    {"glyph": "X", "romanization": "equis", "pronunciation": "eh-kees", "example_glyph": "Xilófono", "example_meaning": "Xylophone", "image": "🎵"},
    {"glyph": "Y", "romanization": "i griega", "pronunciation": "ee gree-eh-gah", "example_glyph": "Yo", "example_meaning": "I", "image": "🙋"},
    {"glyph": "Z", "romanization": "zeta", "pronunciation": "say-tah", "example_glyph": "Zapato", "example_meaning": "Shoe", "image": "👟"},
]

FRENCH_ALPHABET: list[dict] = [
    {"glyph": "A", "romanization": "a", "pronunciation": "ah", "example_glyph": "Avion", "example_meaning": "Airplane", "image": "✈️"},
    {"glyph": "B", "romanization": "bé", "pronunciation": "bay", "example_glyph": "Bonjour", "example_meaning": "Hello", "image": "☀️"},
    {"glyph": "C", "romanization": "cé", "pronunciation": "say", "example_glyph": "Chat", "example_meaning": "Cat", "image": "🐱"},
    {"glyph": "D", "romanization": "dé", "pronunciation": "day", "example_glyph": "Danse", "example_meaning": "Dance", "image": "💃"},
    {"glyph": "E", "romanization": "e", "pronunciation": "uh", "example_glyph": "École", "example_meaning": "School", "image": "🏫"},
    {"glyph": "F", "romanization": "effe", "pronunciation": "eff", "example_glyph": "Fleur", "example_meaning": "Flower", "image": "🌸"},
    {"glyph": "G", "romanization": "gé", "pronunciation": "zhay", "example_glyph": "Gâteau", "example_meaning": "Cake", "image": "🎂"},
    {"glyph": "H", "romanization": "ache", "pronunciation": "ahsh", "example_glyph": "Hôtel", "example_meaning": "Hotel", "image": "🏨"},
    {"glyph": "I", "romanization": "i", "pronunciation": "ee", "example_glyph": "Image", "example_meaning": "Image", "image": "🖼️"},
    {"glyph": "J", "romanization": "ji", "pronunciation": "zhee", "example_glyph": "Jardin", "example_meaning": "Garden", "image": "🌻"},
    {"glyph": "K", "romanization": "ka", "pronunciation": "kah", "example_glyph": "Kilo", "example_meaning": "Kilogram", "image": "⚖️"},
    {"glyph": "L", "romanization": "elle", "pronunciation": "ell", "example_glyph": "Livre", "example_meaning": "Book", "image": "📚"},
    {"glyph": "M", "romanization": "emme", "pronunciation": "em", "example_glyph": "Maison", "example_meaning": "House", "image": "🏠"},
    {"glyph": "N", "romanization": "enne", "pronunciation": "en", "example_glyph": "Nuit", "example_meaning": "Night", "image": "🌙"},
    {"glyph": "O", "romanization": "o", "pronunciation": "oh", "example_glyph": "Orange", "example_meaning": "Orange", "image": "🍊"},
    {"glyph": "P", "romanization": "pé", "pronunciation": "pay", "example_glyph": "Pain", "example_meaning": "Bread", "image": "🍞"},
    {"glyph": "Q", "romanization": "ku", "pronunciation": "koo", "example_glyph": "Quatre", "example_meaning": "Four", "image": "4️⃣"},
    {"glyph": "R", "romanization": "erre", "pronunciation": "air", "example_glyph": "Rouge", "example_meaning": "Red", "image": "🔴"},
    {"glyph": "S", "romanization": "esse", "pronunciation": "ess", "example_glyph": "Soleil", "example_meaning": "Sun", "image": "☀️"},
    {"glyph": "T", "romanization": "té", "pronunciation": "tay", "example_glyph": "Thé", "example_meaning": "Tea", "image": "🍵"},
    {"glyph": "U", "romanization": "u", "pronunciation": "oo", "example_glyph": "Un", "example_meaning": "One", "image": "1️⃣"},
    {"glyph": "V", "romanization": "vé", "pronunciation": "vay", "example_glyph": "Voiture", "example_meaning": "Car", "image": "🚗"},
    {"glyph": "W", "romanization": "double vé", "pronunciation": "doo-bl vay", "example_glyph": "Web", "example_meaning": "Web", "image": "🌐"},
    {"glyph": "X", "romanization": "ixe", "pronunciation": "eeks", "example_glyph": "Xylophone", "example_meaning": "Xylophone", "image": "🎵"},
    {"glyph": "Y", "romanization": "i grec", "pronunciation": "ee grek", "example_glyph": "Yeux", "example_meaning": "Eyes", "image": "👀"},
    {"glyph": "Z", "romanization": "zède", "pronunciation": "zed", "example_glyph": "Zéro", "example_meaning": "Zero", "image": "0️⃣"},
]

GERMAN_ALPHABET: list[dict] = [
    {"glyph": "A", "romanization": "a", "pronunciation": "ah", "example_glyph": "Apfel", "example_meaning": "Apple", "image": "🍎"},
    {"glyph": "B", "romanization": "be", "pronunciation": "bay", "example_glyph": "Brot", "example_meaning": "Bread", "image": "🍞"},
    {"glyph": "C", "romanization": "ce", "pronunciation": "tsay", "example_glyph": "Computer", "example_meaning": "Computer", "image": "💻"},
    {"glyph": "D", "romanization": "de", "pronunciation": "day", "example_glyph": "Danke", "example_meaning": "Thank you", "image": "🙏"},
    {"glyph": "E", "romanization": "e", "pronunciation": "eh", "example_glyph": "Essen", "example_meaning": "Food", "image": "🍽️"},
    {"glyph": "F", "romanization": "ef", "pronunciation": "eff", "example_glyph": "Freund", "example_meaning": "Friend", "image": "👫"},
    {"glyph": "G", "romanization": "ge", "pronunciation": "gay", "example_glyph": "Guten Tag", "example_meaning": "Good day", "image": "☀️"},
    {"glyph": "H", "romanization": "ha", "pronunciation": "hah", "example_glyph": "Haus", "example_meaning": "House", "image": "🏠"},
    {"glyph": "I", "romanization": "i", "pronunciation": "ee", "example_glyph": "Ich", "example_meaning": "I", "image": "🙋"},
    {"glyph": "J", "romanization": "jot", "pronunciation": "yot", "example_glyph": "Ja", "example_meaning": "Yes", "image": "✅"},
    {"glyph": "K", "romanization": "ka", "pronunciation": "kah", "example_glyph": "Kind", "example_meaning": "Child", "image": "👶"},
    {"glyph": "L", "romanization": "el", "pronunciation": "ell", "example_glyph": "Licht", "example_meaning": "Light", "image": "💡"},
    {"glyph": "M", "romanization": "em", "pronunciation": "em", "example_glyph": "Mutter", "example_meaning": "Mother", "image": "👩"},
    {"glyph": "N", "romanization": "en", "pronunciation": "en", "example_glyph": "Nacht", "example_meaning": "Night", "image": "🌙"},
    {"glyph": "O", "romanization": "o", "pronunciation": "oh", "example_glyph": "Oma", "example_meaning": "Grandma", "image": "👵"},
    {"glyph": "P", "romanization": "pe", "pronunciation": "pay", "example_glyph": "Papa", "example_meaning": "Dad", "image": "👨"},
    {"glyph": "Q", "romanization": "ku", "pronunciation": "koo", "example_glyph": "Quelle", "example_meaning": "Source", "image": "💧"},
    {"glyph": "R", "romanization": "er", "pronunciation": "air", "example_glyph": "Rot", "example_meaning": "Red", "image": "🔴"},
    {"glyph": "S", "romanization": "es", "pronunciation": "ess", "example_glyph": "Sonntag", "example_meaning": "Sunday", "image": "📅"},
    {"glyph": "T", "romanization": "te", "pronunciation": "tay", "example_glyph": "Tee", "example_meaning": "Tea", "image": "🍵"},
    {"glyph": "U", "romanization": "u", "pronunciation": "oo", "example_glyph": "Und", "example_meaning": "And", "image": "➕"},
    {"glyph": "V", "romanization": "fau", "pronunciation": "fow", "example_glyph": "Vater", "example_meaning": "Father", "image": "👨‍👧"},
    {"glyph": "W", "romanization": "ve", "pronunciation": "vay", "example_glyph": "Wasser", "example_meaning": "Water", "image": "💧"},
    {"glyph": "X", "romanization": "iks", "pronunciation": "iks", "example_glyph": "Xylophon", "example_meaning": "Xylophone", "image": "🎵"},
    {"glyph": "Y", "romanization": "ypsilon", "pronunciation": "oop-silon", "example_glyph": "Yoga", "example_meaning": "Yoga", "image": "🧘"},
    {"glyph": "Z", "romanization": "tset", "pronunciation": "tset", "example_glyph": "Zug", "example_meaning": "Train", "image": "🚂"},
    {"glyph": "Ä", "romanization": "a-Umlaut", "pronunciation": "eh", "example_glyph": "Mädchen", "example_meaning": "Girl", "image": "👧"},
    {"glyph": "Ö", "romanization": "o-Umlaut", "pronunciation": "er", "example_glyph": "Schön", "example_meaning": "Beautiful", "image": "✨"},
    {"glyph": "Ü", "romanization": "u-Umlaut", "pronunciation": "ue", "example_glyph": "Übung", "example_meaning": "Exercise", "image": "🏋️"},
    {"glyph": "ß", "romanization": "Eszett", "pronunciation": "ess-tset", "example_glyph": "Straße", "example_meaning": "Street", "image": "🛣️"},
]

ITALIAN_ALPHABET: list[dict] = [
    {"glyph": "A", "romanization": "a", "pronunciation": "ah", "example_glyph": "Aereo", "example_meaning": "Airplane", "image": "✈️"},
    {"glyph": "B", "romanization": "bi", "pronunciation": "bee", "example_glyph": "Buongiorno", "example_meaning": "Good morning", "image": "☀️"},
    {"glyph": "C", "romanization": "ci", "pronunciation": "chee", "example_glyph": "Casa", "example_meaning": "House", "image": "🏠"},
    {"glyph": "D", "romanization": "di", "pronunciation": "dee", "example_glyph": "Dolce", "example_meaning": "Sweet", "image": "🍰"},
    {"glyph": "E", "romanization": "e", "pronunciation": "eh", "example_glyph": "Ecco", "example_meaning": "Here", "image": "📍"},
    {"glyph": "F", "romanization": "effe", "pronunciation": "eff-eh", "example_glyph": "Famiglia", "example_meaning": "Family", "image": "👨‍👩‍👧"},
    {"glyph": "G", "romanization": "gi", "pronunciation": "jee", "example_glyph": "Gatto", "example_meaning": "Cat", "image": "🐱"},
    {"glyph": "H", "romanization": "acca", "pronunciation": "ah-kah", "example_glyph": "Hotel", "example_meaning": "Hotel", "image": "🏨"},
    {"glyph": "I", "romanization": "i", "pronunciation": "ee", "example_glyph": "Italia", "example_meaning": "Italy", "image": "🇮🇹"},
    {"glyph": "L", "romanization": "elle", "pronunciation": "el-leh", "example_glyph": "Libro", "example_meaning": "Book", "image": "📚"},
    {"glyph": "M", "romanization": "emme", "pronunciation": "em-meh", "example_glyph": "Mamma", "example_meaning": "Mom", "image": "👩"},
    {"glyph": "N", "romanization": "enne", "pronunciation": "en-neh", "example_glyph": "Notte", "example_meaning": "Night", "image": "🌙"},
    {"glyph": "O", "romanization": "o", "pronunciation": "oh", "example_glyph": "Olio", "example_meaning": "Oil", "image": "🫒"},
    {"glyph": "P", "romanization": "pi", "pronunciation": "pee", "example_glyph": "Pizza", "example_meaning": "Pizza", "image": "🍕"},
    {"glyph": "Q", "romanization": "cu", "pronunciation": "koo", "example_glyph": "Quattro", "example_meaning": "Four", "image": "4️⃣"},
    {"glyph": "R", "romanization": "erre", "pronunciation": "er-reh", "example_glyph": "Rosso", "example_meaning": "Red", "image": "🔴"},
    {"glyph": "S", "romanization": "esse", "pronunciation": "es-seh", "example_glyph": "Sole", "example_meaning": "Sun", "image": "☀️"},
    {"glyph": "T", "romanization": "ti", "pronunciation": "tee", "example_glyph": "Tè", "example_meaning": "Tea", "image": "🍵"},
    {"glyph": "U", "romanization": "u", "pronunciation": "oo", "example_glyph": "Uno", "example_meaning": "One", "image": "1️⃣"},
    {"glyph": "V", "romanization": "vi", "pronunciation": "vee", "example_glyph": "Vino", "example_meaning": "Wine", "image": "🍷"},
    {"glyph": "Z", "romanization": "zeta", "pronunciation": "dzeh-tah", "example_glyph": "Zucchero", "example_meaning": "Sugar", "image": "🍬"},
]

PORTUGUESE_ALPHABET: list[dict] = [
    {"glyph": "A", "romanization": "a", "pronunciation": "ah", "example_glyph": "Avião", "example_meaning": "Airplane", "image": "✈️"},
    {"glyph": "B", "romanization": "bê", "pronunciation": "bay", "example_glyph": "Bom dia", "example_meaning": "Good morning", "image": "☀️"},
    {"glyph": "C", "romanization": "cê", "pronunciation": "say", "example_glyph": "Casa", "example_meaning": "House", "image": "🏠"},
    {"glyph": "D", "romanization": "dê", "pronunciation": "day", "example_glyph": "Dia", "example_meaning": "Day", "image": "📅"},
    {"glyph": "E", "romanization": "e", "pronunciation": "ee", "example_glyph": "Escola", "example_meaning": "School", "image": "🏫"},
    {"glyph": "F", "romanization": "efe", "pronunciation": "eh-fee", "example_glyph": "Família", "example_meaning": "Family", "image": "👨‍👩‍👧"},
    {"glyph": "G", "romanization": "gê", "pronunciation": "zhay", "example_glyph": "Gato", "example_meaning": "Cat", "image": "🐱"},
    {"glyph": "H", "romanization": "agá", "pronunciation": "ah-gah", "example_glyph": "Hoje", "example_meaning": "Today", "image": "📆"},
    {"glyph": "I", "romanization": "i", "pronunciation": "ee", "example_glyph": "Ilha", "example_meaning": "Island", "image": "🏝️"},
    {"glyph": "J", "romanization": "jota", "pronunciation": "zhoh-tah", "example_glyph": "Jardim", "example_meaning": "Garden", "image": "🌻"},
    {"glyph": "L", "romanization": "ele", "pronunciation": "eh-lee", "example_glyph": "Livro", "example_meaning": "Book", "image": "📚"},
    {"glyph": "M", "romanization": "eme", "pronunciation": "eh-mee", "example_glyph": "Mesa", "example_meaning": "Table", "image": "🪑"},
    {"glyph": "N", "romanization": "ene", "pronunciation": "eh-nee", "example_glyph": "Noite", "example_meaning": "Night", "image": "🌙"},
    {"glyph": "O", "romanization": "o", "pronunciation": "oh", "example_glyph": "Olá", "example_meaning": "Hello", "image": "👋"},
    {"glyph": "P", "romanization": "pê", "pronunciation": "pay", "example_glyph": "Pão", "example_meaning": "Bread", "image": "🍞"},
    {"glyph": "Q", "romanization": "quê", "pronunciation": "kay", "example_glyph": "Queijo", "example_meaning": "Cheese", "image": "🧀"},
    {"glyph": "R", "romanization": "erre", "pronunciation": "eh-hee", "example_glyph": "Rio", "example_meaning": "River", "image": "🌊"},
    {"glyph": "S", "romanization": "esse", "pronunciation": "eh-see", "example_glyph": "Sol", "example_meaning": "Sun", "image": "☀️"},
    {"glyph": "T", "romanization": "tê", "pronunciation": "tay", "example_glyph": "Tchau", "example_meaning": "Bye", "image": "👋"},
    {"glyph": "U", "romanization": "u", "pronunciation": "oo", "example_glyph": "Um", "example_meaning": "One", "image": "1️⃣"},
    {"glyph": "V", "romanization": "vê", "pronunciation": "vay", "example_glyph": "Vaca", "example_meaning": "Cow", "image": "🐄"},
    {"glyph": "Z", "romanization": "zê", "pronunciation": "zay", "example_glyph": "Zero", "example_meaning": "Zero", "image": "0️⃣"},
]

LANGUAGE_NAMES = {
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "ja": "Japanese",
    "it": "Italian",
    "pt": "Portuguese",
}

WRITING_SYSTEMS_BY_COURSE: dict[str, list[dict]] = {
    "es": [
        {
            "slug": "alphabet",
            "title": "Alphabet & Pronunciation",
            "description": "Learn the Spanish alphabet and how each letter sounds.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": SPANISH_ALPHABET,
        }
    ],
    "fr": [
        {
            "slug": "alphabet",
            "title": "Alphabet & Pronunciation",
            "description": "Learn the French alphabet and pronunciation.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": FRENCH_ALPHABET,
        }
    ],
    "de": [
        {
            "slug": "alphabet",
            "title": "Alphabet & Special Characters",
            "description": "Learn German letters including Ä, Ö, Ü, and ß.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": GERMAN_ALPHABET,
        }
    ],
    "ja": [
        {
            "slug": "hiragana",
            "title": "Hiragana",
            "description": "Master all 46 hiragana characters.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": HIRAGANA,
        },
        {
            "slug": "katakana",
            "title": "Katakana",
            "description": "Learn katakana for foreign words (unlocks after Hiragana).",
            "order_index": 2,
            "unlock_after_slug": "hiragana",
            "characters": [],
        },
        {
            "slug": "kanji",
            "title": "Kanji",
            "description": "Advanced kanji study (coming soon).",
            "order_index": 3,
            "unlock_after_slug": "katakana",
            "characters": [],
        },
    ],
    "it": [
        {
            "slug": "alphabet",
            "title": "Alphabet & Pronunciation",
            "description": "Learn the Italian alphabet and pronunciation.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": ITALIAN_ALPHABET,
        }
    ],
    "pt": [
        {
            "slug": "alphabet",
            "title": "Alphabet & Pronunciation",
            "description": "Learn the Portuguese alphabet and pronunciation.",
            "order_index": 1,
            "unlock_after_slug": None,
            "characters": PORTUGUESE_ALPHABET,
        }
    ],
}

COURSE_IDS = {
    "es": "c0000000-0000-0000-0000-000000000000",
    "fr": "c1000000-0000-0000-0000-000000000001",
    "de": "c2000000-0000-0000-0000-000000000002",
    "ja": "c3000000-0000-0000-0000-000000000003",
    "it": "c4000000-0000-0000-0000-000000000004",
    "pt": "c5000000-0000-0000-0000-000000000005",
}

COURSE_ID_TO_LANG = {v: k for k, v in COURSE_IDS.items()}
